import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col items-center min-h-screen">
            <h1 className="text-4xl m-4">News Navigator</h1>
            <Nav />
            {children}
            
            <footer>
                <p>Reload for a different topic!</p>
                <br />
                Sourced from:
                <br />
                <a href="https://worldnewsapi.com/">World News API</a>
            </footer>
        </div>


        
        
      </body>
    </html>
  );
}
